### ISSUE TITLE
infer schema from SalesforceObject

### ISSUE THREAD

**Issue by mleuthold** [springml/spark-salesforce#12]
Hi all,

I really like your project and am thrilled to be able to connect Spark with Salesforce. There is just one last thing I miss.

Could SalesforceObject get the feature to have an infered schema as well? As I understand the DataSet of Salesforce Wave supports this right now, but SalesforceObject doesn't.

I would appreciate your clarification on this!

Best regards,
Martin

**Comment by mleuthold** [comment]
Here is what I've got:

SOQL query
`val soql = "select id, amount, CloseDate, CampaignId, ExpectedRevenue, IsClosed, IsDeleted from opportunity LIMIT 100"
`

Schema
> root
 |-- IsDeleted: string (nullable = true)
 |-- ExpectedRevenue: string (nullable = true)
 |-- CampaignId: string (nullable = true)
 |-- Amount: string (nullable = true)
 |-- Id: string (nullable = true)
 |-- IsClosed: string (nullable = true)
 |-- CloseDate: string (nullable = true)

Content of Data Frame
> +---------+---------------+------------------+-------+------------------+--------+----------+
|IsDeleted|ExpectedRevenue|        CampaignId| Amount|                Id|IsClosed| CloseDate|
+---------+---------------+------------------+-------+------------------+--------+----------+
|    false|           null|              null|   null|006w000000hCGTXAA4|    true|2016-01-18|
|    false|           null|              null|   null|006w000000hCGXXAA4|    true|2015-12-18|
|    false|            0.0|701w00000017r9sAAA| 3948.0|006w000000hCHGDAA4|    true|2016-04-21|
|    false|            0.0|701w00000017r9sAAA| 8388.0|006w000000hCHPoAAO|    true|2016-05-12|

**Comment by mikeyoungyoung** [comment]
@mleuthold I am using the infer Schema option for a salesforce object and it "mostly" works (I say mostly because it can't infer dates). Here is what I am using:

`val sfDCOppsDevOrg = devOrg.option("soql", soqlOpps).option("inferSchema", "true").load()`
`root
 |-- ExpectedRevenue: double (nullable = true)
 |-- StageName: string (nullable = true)
 |-- Amount: double (nullable = true)
 |-- Id: string (nullable = true)
 |-- CloseDate: string (nullable = true)
 |-- Name: string (nullable = true)`

**Comment by springml** [comment]
@mikeyoungyoung @mleuthold With this [commit](https://github.com/springml/spark-salesforce/commit/80a62347b4192262886c275bd42361f2bef90b20), inferSchema can now infer TimestampType as well. You need to provide additional option ```dateFormat``` to specify how the timestamps have to be read

**Comment by mikeyoungyoung** [comment]
@springml just digging into this more now, seems like it datetime fields are still loaded as string type. I'm using databricks if that makes a difference. Code is below

`val devOrg = spark.read.format("com.springml.spark.salesforce").option("username", "XXXXXXXXXX").option("password", "XXXXXXXXXXXX")
val temps = "SELECT Name, Obj_Name__r.name, Reading_Taken__c, Temp__c, Type__c FROM Temperature_Reading__c"
val sfDF = devOrg.option("soql", temps).option("inferSchema", true).option("version", "39.0").load()
`
The schema is : 
Obj_Name__r.Name:string
Reading_Taken__c:string
Temp__c:double
Type__c:string
Name:string

Was expecting Reading_Taken to come back as TimeStampType

**Comment by springml** [comment]
@mikeyoungyoung You need to provide the dateFormat option to parse the date. Refer https://github.com/springml/spark-salesforce#options

**Comment by mikeyoungyoung** [comment]
sorry @springml , still not able to get it...(probably due to my lack of experience here ;) ) .  I've added option("dateFormat", "YYYY-MM-DDThh:mm:ss.sssZ") to the dataframe definition above (val sfDF) but it still comes back as a string. If you have an example snippet that works to use soql to load records with a timestamp could you kindly post it here?

**Comment by ravindraSB** [comment]
@mikeyoungyoung I get correct datatype i.e. timestamp with this - 
.option("dateFormat", "yyyy-MM-dd'T'HH:mm:ss.SSS")
